/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ethermanSol from "./Etherman.sol";
export type { ethermanSol };
import type * as swapSol from "./Swap.sol";
export type { swapSol };
import type * as mock from "./mock";
export type { mock };
export type { Multicall3 } from "./Multicall3";
