/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockedERC20__factory } from "./MockedERC20__factory";
export { MockedERC721__factory } from "./MockedERC721__factory";
